# Chapter 8: numpy

`numpy` is perhaps the most important tool in the context of mathematical and scientific python programming. It is a *module*, that is an addition to the python language and needs to be loaded prior to use. In python lingo, we say that we *import* numpy.
`import numpy`
Any function or object defined inside this module can be accessed provided that its name be preceded by the name of the module it belongs to, so for instance, in order to use the `sqrt` function of `numpy`, we use `numpy.sqrt`.



In [2]:
import numpy

print(numpy.sqrt(2))

1.4142135623730951


`numpy` is so ubiquitous that it is traditionally renamed *np* upon importing.

In [5]:
import numpy as np
np.sqrt(2)


np.float64(1.4142135623730951)

## 9.1 `ndarray`

ndarrays are (surprise!) n-dimensional arrays that can be used to represent mathematical quantities. Let's start with a one-dimensional array:


In [10]:
A = [1, 2, 3] # A is a list
B = [4, 5, 6] # B is a list

print('type(A): ', type(A))
print('A + B:   ', A + B)

# Compare with
Anp = np.array([1, 2, 3])
Bnp = np.array([4, 5, 6])
print('type(Anp): ', type(Anp))
print('Anp + Bnp: ', Anp + Bnp)


type(A):  <class 'list'>
A + B:    [1, 2, 3, 4, 5, 6]
type(Anp):  <class 'numpy.ndarray'>
Anp + Bnp:  [5 7 9]


Whereas `+` for python lists means concatenation, `+` for ndarrays means *component-wise* addition. numpy tries to really make any operation component-wise. For those familiar with matlab, this is equivalent to matlab '.' operations

In [17]:
print('Anp * 2:   ', Anp * 2)
print('2 * Anp:   ', 2 * Anp)

print('Anp * Bnp: ', Anp * Bnp)
print('Anp **2:   ', Anp ** 2)

def f(x):
    return 2*x**2-2
print('f(Anp):    ', f(Anp))

Anp * 2:    [2 4 6]
2 * Anp:    [2 4 6]
Anp * Bnp:  [ 4 10 18]
Anp **2:    [1 4 9]
f(Anp):     [ 0  6 16]


ndarray are frequently used to represent data sampled in space or time. Say for instance, that we want to keep track of temperature, pressure, and humidity at n 'points' in time. It would be natural to use a 3 x n ndarray: 

In [ ]:
weather = np.array([[20, 21, 22, 21, 20, 19],
                    [1013, 1025, 1024, 1010, 1000, 990],
                    [20, 30, 30, 40, 2, 25]])

We say that `weather` has 2 *axes* (*i.e.* is *logically 2-dimensional):
Basic information on axes:
* `ndim`: number of axes
* `shape`: length along all axes
* `size`: total number of values

In [ ]:
print("weather:       ", weather)
print("weather.ndim:  ", weather.ndim)
print("weather.shape: ", weather.shape)
print("weather.size:  ", weather.size)

weather:        [[  20   21   22   21   20   19]
 [1013 1025 1024 1010 1000  990]
 [  20   30   30   40    2   25]]
weather.ndim:   2
weather.shape:  (3, 6)
weather.size:   18


3

Think now about keeping track of temperature, pressure, humidity, wind direction and velocity along a three-dimensional grid of points in space for given times. This will take an array with 5 + 3 + 1 = 9 axes. This will be in some sense equivalent to a 9 level nested list.

Note that this means that a np.array must have a fixed dimension along each axis, for instance, 
`[[1, 2, 3], [4, 5]]` is a perfectly fine list but cannot be made into a np.array. 


## 9.2 ndarray vs lists, indexing

Beside the different meaning of `+` and `*`, one fundamental difference between a `np.array` and a nested `list` is indexing. `np.array` are real multidimensional objects whereas nested lists are a bit kludge-y: 

In [28]:
A = [[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]
print(A)
print('A[1][2]:', A[1][2])

print('row 0: ', A[0])
print('col 0: ',[row[0] for row in A])

[[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]
A[1][2]: 5
row 0:  [1, 2, 3, 4]
col 0:  [1, 3, 4]


If a `np.array` has $n$ axes, it can be indexed by $n$ indices instead of taking $n$ sections:

In [ ]:
Anp = np.array(A)
print(Anp)
print('Anp[1][2]:', Anp[1][2])
print('Anp[1,2] :', Anp[1,2])

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]
Anp[1][2]: 5
Anp[1,2] : 5


All rules we saw earlier about indexing work and can be extended to more than one axis

In [45]:
print(Anp)
print('row 0: ', Anp[0,:])
print('col 1: ', Anp[:,1])
print('Anp[0:4:2,:]: ', Anp[0:4:2,:])

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]
row 0:  [1 2 3 4]
col 1:  [2 4 5]
Anp[0:4:2,:]:  [[1 2 3 4]
 [4 5 6 7]]


In [49]:
A = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[10, 11, 12, 13],
               [14, 15, 16, 17]],
              [[20 ,21 ,22, 23],
               [24, 25, 26, 27]]])
print(A)
print('A[0,:,:]: \n', A[0,:,:])
print('A[:,0,:]: \n', A[:,0,:])
print('A[:,:,0]: \n', A[:,:,0])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[10 11 12 13]
  [14 15 16 17]]

 [[20 21 22 23]
  [24 25 26 27]]]
A[0,:,:]: 
 [[0 1 2 3]
 [4 5 6 7]]
A[:,0,:]: 
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
A[:,:,0]: 
 [[ 0  4]
 [10 14]
 [20 24]]


## 9.3 stacking, reshaping
Say that we have two np.arrays of identical length with one axis each and want to combine them
There are really three possible ways to do that: `vstack`, `hstack`, `dstack`.

In [56]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-4, -5, -6], [-7, -8, -9]])
print(np.vstack((A, B)))
print(np.hstack((A, B)))
print(np.dstack((A, B)))

[[ 1  2  3]
 [ 4  5  6]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 1  2  3 -4 -5 -6]
 [ 4  5  6 -7 -8 -9]]
[[[ 1 -4]
  [ 2 -5]
  [ 3 -6]]

 [[ 4 -7]
  [ 5 -8]
  [ 6 -9]]]


Another operation is to *reshape* an array, for instance:

In [65]:
A = [[1, 2, 3], [4, 5, 6]]
print(A)
print(np.reshape(A, (6, 1)))
print(np.reshape(A, (6)))
print(np.reshape(A, (3, 2)))

[[1, 2, 3], [4, 5, 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


## 9.4 Masking / filtering

Boolean operations on a np.array lead to np.arrays of booleans of the same size (this is consistent with the fact that numpy really want to do everything component-wise)
 

In [68]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(A)

print(A%2==0)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


Recall that True is 1 and False is 0

In [69]:
print(A*(A%2==0))

[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]]


In [51]:
print(A[A%2==0])

[ 2  4  6  8 10 12]


## 9.5 Some frequently used arrays

* `zeros`: arrays full of 0s
*  `ones`: array full of 1s
*  `empty`: empty array (useful since ndarrays cannot be extended)
*  `arange`: arrays with a range of numbers. Unlike `range`, elements do not have to be integers
*  `linspace`: arrays with equally spaced elements
*  `eye`: 2D identity matrix

In [81]:
for i in range(3):
    print(i)
    
for i in [0,1,2]:
    print(i)
print(range(3))

# n -> 0, 1, 2, 3, 4, 5 ... n-1]
n = 5


l = []
i = 0
while i < n:
    l.append(i)
    i += 1
print(l)

l = [i for i in range(n)]
print(l)

L = np.arange(1,5,2)

print(L)
print(np.linspace(0,1,5))


0
1
2
0
1
2
range(0, 3)
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[1 3]
[0.   0.25 0.5  0.75 1.  ]


In [82]:
print(np.zeros( (2,3) ))
print(np.empty( (3,3) )) # values are uninitialized and can be anything

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
x = np.linspace(0,1,4)
y = np.linspace(2,3,5)
print(x)
print(y)

[0.         0.33333333 0.66666667 1.        ]
[2.   2.25 2.5  2.75 3.  ]
