# Monday March 2nd 2026

## Announcements 
- Assignment 3 due on March 11th, at 11:59pm
- Midterm 2 Thursday March 12th, 7:00pm-9:00pm in KTH B135 (Note the different room!)

## Last time - List Comprehension

List comprehension syntax allows us to quickly create structured lists from other iterable collections. The syntax closely mirrors **set-builder** syntax you may have seen in a mathematics course. 

### Warmup exercise

Create a list of the first $100$ perfect squares.
1. Using a for loop.
2. Using a list comprehension

In [21]:
# for loop
squares = []
for i in range(101):
    squares.append(i**2)

In [ ]:
# list comprehension
squares = [i**2 for i in range(101)]

How do these two solutions vary? What is the most computational intensive step? **Hint:** How are lists stored?

### Exercise

Create a list of all **Pythagorean triples** smaller than $100$. 

**Recall:** A triple of natural numbers $a,b,c$ is called a Pythagorean triple if $a^2+b^2=c^2$. i.e. if $a$, $b$, and $c$ can be the lengths of the sides of a right angled triangle.

In [24]:
triples = [
    (a,b,c)
    for a in range(1,101)
    for b in range(1,101)
    for c in range(1,101)
    if a**2 + b**2 == c**2
]

print(triples)

[(3, 4, 5), (4, 3, 5), (5, 12, 13), (6, 8, 10), (7, 24, 25), (8, 6, 10), (8, 15, 17), (9, 12, 15), (9, 40, 41), (10, 24, 26), (11, 60, 61), (12, 5, 13), (12, 9, 15), (12, 16, 20), (12, 35, 37), (13, 84, 85), (14, 48, 50), (15, 8, 17), (15, 20, 25), (15, 36, 39), (16, 12, 20), (16, 30, 34), (16, 63, 65), (18, 24, 30), (18, 80, 82), (20, 15, 25), (20, 21, 29), (20, 48, 52), (21, 20, 29), (21, 28, 35), (21, 72, 75), (24, 7, 25), (24, 10, 26), (24, 18, 30), (24, 32, 40), (24, 45, 51), (24, 70, 74), (25, 60, 65), (27, 36, 45), (28, 21, 35), (28, 45, 53), (28, 96, 100), (30, 16, 34), (30, 40, 50), (30, 72, 78), (32, 24, 40), (32, 60, 68), (33, 44, 55), (33, 56, 65), (35, 12, 37), (35, 84, 91), (36, 15, 39), (36, 27, 45), (36, 48, 60), (36, 77, 85), (39, 52, 65), (39, 80, 89), (40, 9, 41), (40, 30, 50), (40, 42, 58), (40, 75, 85), (42, 40, 58), (42, 56, 70), (44, 33, 55), (45, 24, 51), (45, 28, 53), (45, 60, 75), (48, 14, 50), (48, 20, 52), (48, 36, 60), (48, 55, 73), (48, 64, 80), (51, 68, 8

In [ ]:
triples = [
    (a, b, c)
    for a in range(1,101)
    for b in range(1,101)
    for c in range(1,101)
    if a**2+b**2==c**2
    ]
print(triples)

**Note:** Comprehension syntax works for other container types in Python like sets and dictionaries! However, `()` does not denote a tuple comprehension. This is called a *generator expression*.

**Recall:** The `range()` function is a nice piece of Python syntax as it offers a quick way of creating structured containers of integers. However, there is something else that is different between the following two objects:

In [ ]:
for i in range(1000):
    if i > 10:
        break

In [ ]:
# spot the difference!
range(1,6)
[1,2,3,4,5]

In [ ]:
# this is a list comprehension
sum([i for i in range(101)])
# this is a generator expression
sum((i for i in range(101)))

# Chapter 8: numpy

`numpy` is perhaps the most important tool in the context of mathematical and scientific python programming. It is a *module*, that is an addition to the python language and needs to be loaded prior to use. In python lingo, we say that we *import* numpy.
`import numpy`
Any function or object defined inside this module can be accessed provided that its name be preceded by the name of the module it belongs to, so for instance, in order to use the `sqrt` function of `numpy`, we use `numpy.sqrt`.



In [25]:
import numpy

print(numpy.sqrt(2))

1.4142135623730951


`numpy` is so ubiquitous that it is traditionally renamed *np* upon importing.

In [26]:
import numpy as np
print(np.sqrt(2))

1.4142135623730951


In [27]:
print(np.pi)

3.141592653589793


In [ ]:
L = [1,2,3,'str',[1,2,3]]

In [ ]:
matr = [[1,2,3],[2,3,4],[5,6,7]]

matr2 = [[1,2,3],[2,3,4][5,6]]

numericals = [[1,2],[3.4,5]]

Numpy gives us access to many useful mathematical functions. However, most fundamentally they introduce a new type, the **n-dimensional array**.

The **nd-array** has three key design features:
- It is a homogeneous container
- It must have a regular shape (all rows and columns must have the same length i.e. no jagged edges)
- It has constant size

Note that these three features directly contrast with Python's list implementation. All of these restrictions lead to greater efficiency especially when dealing with large data. 

## 9.1 `ndarray`

Let's start with a one-dimensional array:


In [28]:
A = [1, 2, 3] # A is a list
B = [4, 5, 6] # B is a list

print('type(A): ', type(A))
print('A + B:   ', A + B)

# Compare with
Anp = np.array([1, 2, 3])
Bnp = np.array([4, 5, 6])
print('type(Anp): ', type(Anp))
print('Anp + Bnp: ', Anp + Bnp)


type(A):  <class 'list'>
A + B:    [1, 2, 3, 4, 5, 6]
type(Anp):  <class 'numpy.ndarray'>
Anp + Bnp:  [5 7 9]


Whereas `+` for python lists means concatenation, `+` for ndarrays means *component-wise* addition. numpy tries to really make any operation component-wise. For those familiar with matlab, this is equivalent to matlab '.' operations

We usually call these *component-wise* operations **vectorized** operations.

In [29]:
print(Anp)
print('Anp * 2:   ', Anp * 2)
print('2 * Anp:   ', 2 * Anp)

# Note: This is component-wise multiplication
# for normal matrix multiplication we use @
print('Anp * Bnp: ', Anp * Bnp)
print('Anp **2:   ', Anp ** 2)

def f(x):
    return 2*x**2-2
print('f(Anp):    ', f(Anp))

[1 2 3]
Anp * 2:    [2 4 6]
2 * Anp:    [2 4 6]
Anp * Bnp:  [ 4 10 18]
Anp **2:    [1 4 9]
f(Anp):     [ 0  6 16]


ndarray are frequently used to represent data sampled in space or time. Say for instance, that we want to keep track of temperature, pressure, and humidity at n 'points' in time. It would be natural to use a 3 x n ndarray: 

In [30]:
weather = np.array([[20, 21, 22, 21, 20, 19],
                    [1013, 1025, 1024, 1010, 1000, 990],
                    [20, 30, 30, 40, 2, 25]])

We say that `weather` has 2 *axes* (*i.e.* is *logically 2-dimensional):
Basic information on axes:
* `ndim`: number of axes
* `shape`: length along all axes
* `size`: total number of values

In [31]:
print("weather:       ", weather)
print("weather.ndim:  ", weather.ndim)
print("weather.shape: ", weather.shape)
print("weather.size:  ", weather.size)

weather:        [[  20   21   22   21   20   19]
 [1013 1025 1024 1010 1000  990]
 [  20   30   30   40    2   25]]
weather.ndim:   2
weather.shape:  (3, 6)
weather.size:   18


Think now about keeping track of temperature, pressure, humidity, wind direction and velocity along a three-dimensional grid of points in space for given times. This will take an array with 5 + 3 + 1 = 9 axes. This will be in some sense equivalent to a 9 level nested list.

Note that this means that a np.array must have a fixed dimension along each axis, for instance, 
`[[1, 2, 3], [4, 5]]` is a perfectly fine list but cannot be made into a np.array. 


## 9.2 ndarray vs lists, indexing

Beside the different meaning of `+` and `*`, one fundamental difference between a `np.array` and a nested `list` is indexing. `np.array` are real multidimensional objects whereas nested lists are a bit kludge-y: 

In [32]:
A = [[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]
print(A)
print('A[1][2]:', A[1][2])

print('row 0: ', A[0])
print('col 0: ',[row[0] for row in A])

[[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]
A[1][2]: 5
row 0:  [1, 2, 3, 4]
col 0:  [1, 3, 4]


If a `np.array` has $n$ axes, it can be indexed by $n$ indices instead of taking $n$ sections:

In [33]:
Anp = np.array(A)
print(Anp)
print('Anp[1][2]:', Anp[1][2])
print('Anp[1,2] :', Anp[1,2])

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]
Anp[1][2]: 5
Anp[1,2] : 5


All rules we saw earlier about indexing work and can be extended to more than one axis

In [35]:
print(Anp)
print('row 0: ', Anp[0,:])
print('col 1: ', Anp[:,1])
print('Anp[0:4:2,:]: ', Anp[0:4:2,:])

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]
row 0:  [1 2 3 4]
col 1:  [2 4 5]
Anp[0:4:2,:]:  [[1 2 3 4]
 [4 5 6 7]]


In [36]:
A = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[10, 11, 12, 13],
               [14, 15, 16, 17]],
              [[20 ,21 ,22, 23],
               [24, 25, 26, 27]]])
print(A)
print('A[0,:,:]: \n', A[0,:,:])
print('A[:,0,:]: \n', A[:,0,:])
print('A[:,:,0]: \n', A[:,:,0])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[10 11 12 13]
  [14 15 16 17]]

 [[20 21 22 23]
  [24 25 26 27]]]
A[0,:,:]: 
 [[0 1 2 3]
 [4 5 6 7]]
A[:,0,:]: 
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
A[:,:,0]: 
 [[ 0  4]
 [10 14]
 [20 24]]


### Exercise

Given a $3\times 3$ matrix extract the minors.

In [37]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# Minor A11
print(A[1:,1:])

[[5 6]
 [8 9]]


In [39]:
# Minor A12
print(A[::2, 1:])

[[2 3]
 [8 9]]


In [ ]:
# Minor A13
print(A[:2,1:])

[[2 3]
 [5 6]]


In [ ]:
def det_2by2_or3by3(m):
    if m.shape() == (2,2):
        return m[0,0]*m[1,1]-m[0,1]*m[1,0]
    else:
        return det_2by2_or3by3(m[1:,1:]) - det_2by2_or3by3(m[::2, 1:])+ det_2by2_or3by3(m[:2,1:])

In [ ]:
def det3by3(A):
    det_2by2(A[1:,1:]) - det_2by2(A[::2, 1:])+ det_2by2(A[:2,1:])

In [ ]:
# Extract M11

print(A[1:,1:])

# Extract M12

print(A[1:,::2])
# Extract M13

print(A[1:,:-1])

### Exercise

Write a function `det()` which returns the determinant of a $3\times 3$ matrix.

In [ ]:
def det():

    return None

## 9.3 stacking, reshaping
Say that we have two np.arrays of identical length with one axis each and want to combine them
There are really three possible ways to do that: `vstack`, `hstack`, `dstack`.

In [42]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-4, -5, -6], [-7, -8, -9]])
print(np.vstack((A, B)))
print(np.hstack((A, B)))
print(np.dstack((A, B)))

[[ 1  2  3]
 [ 4  5  6]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 1  2  3 -4 -5 -6]
 [ 4  5  6 -7 -8 -9]]
[[[ 1 -4]
  [ 2 -5]
  [ 3 -6]]

 [[ 4 -7]
  [ 5 -8]
  [ 6 -9]]]


Another operation is to *reshape* an array, for instance:

In [44]:
A = [[1, 2, 3], [4, 5, 6]]
print(A)
print(np.reshape(A, (6, 1)))
print(np.reshape(A, (6)))
print(np.reshape(A, (3, 2)))
print(np.reshape(A,(2,2)))

[[1, 2, 3], [4, 5, 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


ValueError: cannot reshape array of size 6 into shape (2,2)

## 9.4 Masking / filtering

Boolean operations on a np.array lead to np.arrays of booleans of the same size (this is consistent with the fact that numpy really want to do everything component-wise)
 

In [45]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(A)

print(A%2==0)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


Recall that True is 1 and False is 0

In [46]:
print(A*(A%2==0))

[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]]


In [ ]:
print(A[A%2==0])

## 9.5 Some frequently used arrays

* `zeros`: arrays full of 0s
*  `ones`: array full of 1s
*  `empty`: empty array (useful since ndarrays cannot be extended)
*  `arange`: arrays with a range of numbers. Unlike `range`, elements do not have to be integers
*  `linspace`: arrays with equally spaced elements
*  `eye`: 2D identity matrix

In [ ]:
for i in range(3):
    print(i)
    
for i in [0,1,2]:
    print(i)
print(range(3))

# n -> 0, 1, 2, 3, 4, 5 ... n-1]
n = 5


l = []
i = 0
while i < n:
    l.append(i)
    i += 1
print(l)

l = [i for i in range(n)]
print(l)

L = np.arange(1,5,2)

print(L)
print(np.linspace(0,1,5))


In [ ]:
print(np.zeros( (2,3) ))
print(np.empty( (3,3) )) # values are uninitialized and can be anything

In [ ]:
x = np.linspace(0,1,4)
y = np.linspace(2,3,5)
print(x)
print(y)